# Generated by Django 3.2.6 on 2021-10-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ユーザー名'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='user',
            field=models.CharField(max_length=50, verbose_name='MACアドレス'),
        ),
    ]
