# Generated by Django 4.0 on 2021-12-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0002_auto_20211012_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='user_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ユーザー名'),
        ),
    ]
